version: '3.1'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: semplify
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - semplify

  keycloak:
    image: jboss/keycloak
    hostname: keycloak
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: semplify
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: H2
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/data
    networks:
      - semplify

volumes:
  mongo:
  keycloak:

networks:
  semplify:
