version: '3.1'
services:

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: semplify
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - semplify

  keycloak:
    image: jboss/keycloak
    hostname: keycloak
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: semplify
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: H2
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/data
    networks:
      - semplify

  virtuoso:
    image: tenforce/virtuoso
    hostname: virtuoso
    container_name: virtuoso
    environment:
      SPARQL_UPDATE: "true"
      VIRT_Parameters_NumberOfBuffers: 1360000
      VIRT_Parameters_MaxDirtyBuffers: 1000000
    volumes:
      - virtuoso:/data
    ports:
      - 8890:8890
      - 1111:1111

volumes:
  mongo:
  keycloak:
  virtuoso:

networks:
  semplify:
