version: '3.1'
services:

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: semplify
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - semplify

  keycloak:
    image: jboss/keycloak
    hostname: keycloak
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: semplify
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: H2
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/data
    networks:
      - semplify

  rdf4j:
    image: tonhudung/rdf4j:3.2.0
    hostname: rdf4j
    container_name: rdf4j
    environment:
      JAVA_OPTS: '-Xms16g -Xmx32g'
    ports:
      - 8090:8080
    volumes:
      - rdf4j_data:/var/rdf4j
      - rdf4j_logs:/usr/local/tomcat/logs
    networks:
      - semplify

  virtuoso:
    image: tenforce/virtuoso
    hostname: virtuoso
    container_name: virtuoso
    environment:
      SPARQL_UPDATE: "true"
      VIRT_Parameters_NumberOfBuffers: 2720000
      VIRT_Parameters_MaxDirtyBuffers: 2000000
    volumes:
      - virtuoso:/data
    ports:
      - 8890:8890
      - 1111:1111
    networks:
      - semplify

  virtuoso-det:
    image: tenforce/virtuoso
    hostname: virtuoso-det
    container_name: virtuoso-det
    environment:
      SPARQL_UPDATE: "true"
      VIRT_Parameters_NumberOfBuffers: 340000
      VIRT_Parameters_MaxDirtyBuffers: 250000
    volumes:
      - virtuoso-det:/data
    ports:
      - 8891:8890
      - 1112:1111
    networks:
      - semplify

#  semplify:
#    image: tonhudung/semplify
#    build:
#      context: ./semplify
#      args:
#        REACT_APP_KEYCLOAK_URL: "http://alexto.ddns.net:8080/auth"
#        REACT_APP_KEYCLOAK_REALM: "semplify"
#        REACT_APP_KEYCLOAK_CLIENT_ID: "semplify-ui"
#    hostname: semplify
#    container_name: semplify
#    environment:
#      SEMPLIFY_KEYCLOAK_DISCOVERY_URI: "http://alexto.ddns.net:8080/auth/realms/semplify/.well-known/openid-configuration"
#      SEMPLIFY_KEYCLOAK_CLIENT_ID: "semplify-services"
#      SEMPLIFY_RDF4J_URL: "http://rdf4j:8080/rdf4j-server"
#      SEMPLIFY_MONGO_URL: "mongodb://mongo:27017/semplify"
#      SEMPLIFY_KEYCLOAK_SECRET: "a82a412d-a847-497e-9423-705910239e4b"
#    ports:
#      - 9000:9000
#    networks:
#      - semplify

volumes:
  mongo:
  keycloak:
  virtuoso:
  virtuoso-det:
  rdf4j_data:
  rdf4j_logs:

networks:
  semplify:
